# Perfil de Desarrollo (Entorno Local)

# Conexión a SQL Server Local
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_LimaTambo;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false;
spring.datasource.username=admin_clinica
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Nunca modificar ni borrar la estructura de la base de datos local
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
