# Configuración para PostgreSQL en Render
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Importante: Como la base de datos en Render estará vacía al principio,
# le decimos a Spring Boot que cree las tablas automáticamente.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Mantenemos la configuración del correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=draverla2002@gmail.com
spring.mail.password=itpb jrey clmw fqlb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
