# Perfil activo por defecto (local)
spring.profiles.active=dev

# Configuración de Correo Electrónico compartida
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=draverla2002@gmail.com
spring.mail.password=geah bauh giuk thdo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Cambiando el puerto para no interferir con tu otro proyecto en VS Code
server.port=${PORT:8081}