# === CONFIGURACION DE BASE DE DATOS EN MEMORIA (H2) PARA DEPLOY/TESTING ===
spring.datasource.url=jdbc:h2:mem:clinicadb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === CONFIGURACION ORIGINAL SQL SERVER (Descomentar para usar en local con SQL Server) ===
# spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=DB_LimaTambo;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false;}
# spring.datasource.username=${DB_USERNAME:admin_clinica}
# spring.datasource.password=${DB_PASSWORD:123456}
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cambiando el puerto para no interferir con tu otro proyecto en VS Code
server.port=8081

# Configuración de Correo Electrónico (Para Recuperar Contraseña)
# POR HACER: Reemplaza tucorreo@gmail.com y tu_contraseña_de_aplicacion
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=draverla2002@gmail.com
spring.mail.password=itpb jrey clmw fqlb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true